src/core/users/DisplayPrice.ts
src/services/PaymentService.ts
tests/src/controller.test.ts

Include the price currency, so we don't hardcode this values in the client side

[_]: Include the price currency when getting all the prices

---

src/controller.ts
src/services/PaymentService.ts

Coupon code added into /checkout-session path for obtain the discount

[_]:(feature) Adding coupon code param into /checkout-session path

---

src/controller.ts
src/services/PaymentService.ts

- Allows checkout session mode to be injected

[_]: feat/allow-mode-to-be-injected

---

src/core/users/DisplayPrice.ts
src/services/PaymentService.ts

Changes: 
- Exposes lifetime prices
Stripe documentation references:
- [Pricing models](https://stripe.com/docs/products-prices/pricing-models)
- [Prices Search Query Language](https://stripe.com/docs/search#search-query-language)

[_]: feat/lifetimes-prices

---

src/controller.ts
src/services/PaymentService.ts

A trial parameter has been added to allow the user to have free days/months.

[_]: feat/add-optional-free-trial-param

---

src/controller.ts
src/services/PaymentService.ts

Missing data for free trial option has been added.

[_]: fix/Free trial param fixed

---

src/controller.ts
src/services/PaymentService.ts

Apply couponCode when the user is elegible and has an active subscription.

[PB-243]: feat/apply-coupon-to-given-user

---

src/services/PaymentService.ts

Fix the amoutAfterCoupon parameter to get the actual price of the next invoice.

[_]: fix/Fix amountAfterCoupon param

---

src/services/PaymentService.ts

Create invoices for one-time payments.

[_]: fix/Create invoice when user buy lifetime plan

---

src/controller.ts
src/core/users/MongoDBLicenseCodesRepository.ts
src/services/LicenseCodesService.ts

New call added to check if the unique code is available or not to avoid creating user if it is not available.

[_]: feat/check-unique-codes

---

src/controller.ts
src/core/users/MongoDBLicenseCodesRepository.ts
src/services/LicenseCodesService.ts

Revert "[_]: feat/check-unique-codes"

---

src/controller.ts
src/core/users/MongoDBLicenseCodesRepository.ts
src/services/LicenseCodesService.ts
tests/src/controller.test.ts

Adds the option to check if an EPC is available

[_]: feat/check-if-unique-code-is-valid

---

.env.template
infrastructure/development.Dockerfile

These changes introduce small adaptations for the new dev environment

[PB-597]: dev-environment

---

src/services/PaymentService.ts

Changes: 
- Fixes a bug related to not applying the trial period at the end of the last active subscription.

[_]: fix/apply-trial-from-end-of-subscription

---

package.json
src/cli/load-license-codes.ts
src/controller.ts
src/server.ts
src/services/PaymentService.ts
tests/src/controller.test.ts
yarn.lock

New payments methods:
* bancontact 
* ideal
* sofort
* paypal

[MKT-115]: feat/new payments methods on Stripe

---

src/services/PaymentService.ts

Paypal removed for checkout session

[_]: fix/Remove paypal from payments method types

---

src/controller.ts
src/services/PaymentService.ts
src/services/StorageService.ts
src/webhooks/handleCheckoutSessionCompleted.ts
src/webhooks/handleSetupIntentCompleted.ts
src/webhooks/handleSubscriptionUpdated.ts
src/webhooks/index.ts

Allow users to purchase a subscription or lifetime plan with PayPal.

[MKT-125]: feat/Paypal payment method

---

src/controller.ts
src/services/PaymentService.ts

Allow the user to update his subscription with discount (allow coupon code).

[_]: fix/update subscription with coupon code

---

src/services/PaymentService.ts

**PROBLEM:**
The user does not pay the correct amount for each plan when upgrading the plan.
**FIX:**
Now, every time the user switches to another plan, he will pay the full price.

[_]: Fix/remove balance when switching plan

---

src/services/PaymentService.ts

Fixed the flow to prevent-cancellation endpoint. Removed trial_end parameter and checked if payment_intent exists in order to avoid unexpected errors.

[_]: fix/prevent cancellation error

---

src/services/PaymentService.ts

Revert "[_]: fix/prevent cancellation error"

---

src/controller.ts
src/services/PaymentService.ts
src/webhooks/index.ts

Revert "[_]: fix/remove billing cycle param"

---

src/services/PaymentService.ts

New payment methods for one time payment are added:
* Alipay
* Eps
* Giropay
* Klarna

[MKT-168]: feat/add more payment methods for one time payments

---

src/controller.ts
src/services/PaymentService.ts
tests/src/services/UsersService.test.ts

Now, the user can get the prices in USD if coming from USA. 
In addition, the user can pay with USD currency and Stripe will do the conversion automatically.

[MKT-218]: feat/allow the user get and pay with USD prices

---

src/services/PaymentService.ts

Get the correct price depending on the currency. 
Now, we have just one product with multi currency and we get the price depending on the currency we sent from the front end.

[_]: fix/compatibility-for-pricing-with-multiple-currencies

---

src/controller.ts
src/core/users/MongoDBDisplayBillingRepository.ts
src/server.ts
src/services/UsersService.ts

Changes: 
- Expose a flag to manage the visibility of the billing in some client apps

[_]: feat/display-billing-remotely

---

src/cli/load-license-codes.ts
src/controller.ts
src/core/coupons/Coupon.ts
src/core/coupons/CouponsRepository.ts
src/core/coupons/MongoDBCouponsRepository.ts
src/core/coupons/MongoDBUsersCouponsRepository.ts
src/core/coupons/UserCoupon.ts
src/core/coupons/UsersCouponsRepository.ts
src/core/users/MongoDBUsersRepository.ts
src/core/users/User.ts
src/core/users/UsersRepository.ts
src/server.ts
src/services/UsersService.ts

Changes: 
- Add coupon tracking system base
- Add endpoint to check if a coupon has already been used

[_]: feat/add-coupons-tracking-system

---

src/controller.ts
src/core/coupons/MongoDBUsersCouponsRepository.ts
src/services/PaymentService.ts
src/services/UsersService.ts
src/webhooks/handleCheckoutSessionCompleted.ts
src/webhooks/handleSubscriptionUpdated.ts
src/webhooks/index.ts

Adding new method to store a new entry on the history of coupons used by a given user when `checkout.subscription.updated` webhook is triggered.

[_]: feat/add method in webhook

---

src/webhooks/handleCheckoutSessionCompleted.ts

Add logs to track the checkout webhook.

[_]: feat/add logs

---

src/controller.ts
src/services/PaymentService.ts

Allow the retrieval of specific subscription invoices by specifying a subscriptionId in the query string. Not specifying anything will return all of the customer's invoices.

[PB-2120]: feat/get b2b invoices

---

src/controller.ts
src/services/PaymentService.ts

Allow the retrieval of available b2b plans based on the queryString subscribptionType. If the queryString where not provided individual plans would be returned by default.

[PB-2266]: feat/retrieve available b2b subscriptions

---

src/controller.ts
src/core/users/User.ts
src/services/CacheService.ts
src/services/PaymentService.ts
src/webhooks/handleCheckoutSessionCompleted.ts
src/webhooks/handleSubscriptionCanceled.ts

- Integrate `UserType` in endpoints and methods.
- Add `plan` field inside the endpoint `GET susbscriptions` to avoid another call from the `drive-server` to get the plan information.

Chore: update b2b methods

---

src/services/PaymentService.ts

Ability to adjust subscrption/seat quanity during checkout

fix: make quantity adjustable on stripe checkout

---

src/services/UsersService.ts
src/webhooks/handleSubscriptionUpdated.ts

Add number of seats in the Post request that creates the worksapce.

fix: send number of seats to gateway that creates new workspaces

---

src/controller.ts
src/services/PaymentService.ts
src/services/UsersService.ts
src/webhooks/handleCheckoutSessionCompleted.ts

Endpoint to allow the editing of a custumer's billing address and phone number. Also send the phone number to drive's gateway that creates a workspace upon succesful checkout

fix: edit billing details

---

src/controller.ts
src/services/PaymentService.ts
src/webhooks/handleCheckoutSessionCompleted.ts
src/webhooks/handlePaymentIntentCompleted.ts
src/webhooks/handleSubscriptionUpdated.ts

Cancelling the active subscription if user decides to switch from subscription to lifetime and allowing multi currencies for payments.

[_]: fix/handle payment intent completed

---

src/webhooks/handleInvoiceCompleted.ts
src/webhooks/index.ts

Change of the webhook event to when the user purchases a plan with a 100% discount. This new event applies to all cases.

[_]: fix/change webhook event

---

src/controller.ts
src/services/PaymentService.ts
src/webhooks/handleInvoiceCompleted.ts
src/webhooks/handleSubscriptionUpdated.ts
src/webhooks/index.ts

Check if the coupon can be used for each case:
- If it is for first purchase only.
- If it is for a specific plan.
Also a try catch has been added to the function that handles the customer.subscription.updated event so that it doesn't always pop a 500.

[MKT-413]: fix/coupon codes

---

src/cli/load-license-codes.ts

Adding missing properties to PaymentService object for load-license-codes file.

[_]: fix/deployment

---

src/controller.ts
src/services/PaymentService.ts

An endpoint has been enabled to obtain coupon information on the website without the need to pass a plan.

[_]: fix/endpoint for promotion codes

---

src/services/PaymentService.ts
src/webhooks/handleInvoiceCompleted.ts

Obtain the coupon used by user from the line items instead of the invoice as it does not appear on the invoice.

[_]: fix: store coupon used by user in handleInvoiceCheckout

---

src/webhooks/handleInvoiceCompleted.ts

Allow to add the customer to the collection in invoice.payment_succeeded in order to find his information by customer ID.

[_]: fix/allow-customer-creation-when-missing-on-payment-succeeded

---

src/services/PaymentService.ts

Checking the type of subscription and not if there is any type of subscription (free/subscription/lifetime).

[_]: fix/check the subscription type before creating sub

---

src/services/PaymentService.ts

- Added subscriptionId and paymentIntentId to return types when create payment type subscription

[_] : bugfix/Fix impact in integrated checkout

---

src/services/PaymentService.ts

- Return subscription id always when create a subscription

[_]: Return subscription id always when create a subscription

---

src/controller.ts

Creation of a new endpoint to create a subscription in the object storage checkout.

[_]: feat/endpoint to create sub for obj storage

---

src/controller.ts
src/services/PaymentService.ts

Checking if the customer who wants to purchase a object storage plan, is already a Stripe customer to avoid multiple customers with the same email.

[_]: fix/check if customer exists before creating one

---

src/services/PaymentService.ts

Return the existing customer and do not create a new one when trying to create a customer for obj storage.

[_]: fix/return the existing customer and not an Error

---

src/controller.ts
src/services/PaymentService.ts

Now, companies can add a couple of parameters when they want to buy a b2b subscription or a subscription for obj storage, which are as follows:
* Company name
* Company Vat ID

[MKT-417]: feat/optional params for companies

---

src/controller.ts
src/services/PaymentService.ts
src/webhooks/handleSubscriptionUpdated.ts

Attach the Tax ID of the company when creating the customer, if these fields are provided (country and vatId).

[_]: feat/attaching the company tax ID to the customer data

---

src/controller.ts
src/services/PaymentService.ts

send error messages to find out what is going wrong in the integrated checkout flow.

[_]: fix/send error messages when creating subscription endpoint fails

---

src/controller.ts
src/services/PaymentService.ts

Obtaining the existing customer if it exists before creating a new one.

[_]: feat/get the customer if it exists when creating customer

---

src/controller.ts
src/core/users/User.ts
src/services/PaymentService.ts
src/webhooks/handleInvoiceCompleted.ts
src/webhooks/handleSubscriptionUpdated.ts

Modifying the create customer and subscription endpoints to get all necessary data for B2B subscription. The webhook event `invoice.succeeeded` and `customer.subscription.updated` has also been modified to manage the B2C and B2B cases.

[MKT-429]: feat/modifying create customer and subscription for B2B subscriptions

---

src/controller.ts
src/services/PaymentService.ts
src/webhooks/handleSubscriptionUpdated.ts
tests/src/services/PaymentService.test.ts

Throwing custom error when the provided Tax ID is invalid.

[_]: feat/throw custom error when the Tax ID is invalid

---

Dockerfile
infrastructure/development.Dockerfile
infrastructure/preview.Dockerfile
package.json
src/app.ts
src/webhooks/handleInvoiceCompleted.ts
tsconfig.json

- Solves https://github.com/internxt/payments-server/issues/122
- Changes in tsconfig:
- `target`: Updated to ES2022 to leverage modern JavaScript features supported by Node.js 18+.
- `lib`: Updated to ES2022 to align with the runtime environment and provide access to the latest APIs.

[_]: feat/upgrade-to-Node-20

---

src/controller/business.controller.ts
src/services/users.service.ts

Sending the `workspaceId` to `isWorkspaceUpgradeAllowed` endpoint (gateway) to check if the workspace is elegible or not to update the members.

[_]: fix/send the workspaceID to check if workspace can be updated

---

.github/workflows/sonarcloud-analysis.yml
sonar-project.properties

This PR adds integration with SonarCloud to the project to ensure code quality. SonarCloud allows to identify bugs, vulnerabilities, and improve test coverage on every Pull Request. This helps reduce technical debt, maintain high standards, and ensure cleaner and more secure code during development.

[_]: feat/Sonarcloud analysis

---

.github/workflows/pr-size-control.yml

This PR adds an Action to enforce less than 500 LOCs changed on a given PR

[_]: feat/pr-size-control [skip ci]

---

package.json
src/server.ts
src/services/payment.service.ts
tests/src/controller.test.ts
tests/src/mocks/index.ts
tests/src/payments.controller.test.ts
tests/src/utils/factory.ts
tests/src/utils/preloadMongoDBData.ts
yarn.lock

Adding tests for `payment.controller.ts` and enabling the Sonarcloud coverage.

[_]: tests/payment controller coverage

---

src/core/users/MongoDBTiersRepository.ts
src/services/tiers.service.ts
tests/src/mocks/index.ts
tests/src/services/tiers.service.test.ts
tests/src/utils/factory.ts

A tiers domain is created to prepare this server to handle multiple features being applied per product. The tier entity is the following:
```
interface Tier {
label: string;
productId: string;
billingType: "subscription" | "lifetime",
featuresPerService: {
[Service.Drive]: DriveFeatures,
[Service.Backups]: BackupsFeatures,
[Service.Antivirus]: AntivirusFeatures,
[Service.Meet]: MeetFeatures,
[Service.Mail]: MailFeatures,
[Service.Vpn]: VpnFeatures
}
}
```
It allows defining features per product, linked to a specific product ID (e.g., from Stripe). This enables setting product-specific features while keeping the service simple by delegating feature application to each service backend. 
NOTE: This is not connected still. The idea is to replace the successful payment creation/update webhooks …

[_]: feat/tiers-per-product

---

src/app.ts
src/controller/prodcuts.controller.ts
src/controller/products.controller.ts
src/server.ts
src/services/tiers.service.ts
tests/src/services/tiers.service.test.ts

Get the products that the user can access depending on whether it is a lifetime plan or has a subscription. 
At the moment we only give back whether he is eligible for the antivirus or not.

[_]: feat/get products depending on the user subscription or lifetime

---

src/controller/products.controller.ts
src/services/tiers.service.ts
tests/src/services/tiers.service.test.ts

check if the user can use the antivirus using the product ID of each plan or if he has an active lifetime.

[PB-3724]: feat/check if the user can use the antivirus using the product ID of each plan

---

tests/src/fixtures.spec.ts
tests/src/fixtures.ts

This PR improves the existing test fixtures by adding more detailed and accurate data to better emulate real Stripe API responses. These enhancements ensure greater test reliability and consistency when validating business logic.

[_]: feat/improving-fixtures

---

tests/src/services/users.service.test.ts

This PR updates the user service tests to utilize the existing fixtures, improving test consistency and maintainability.

[_]: tests/fixtures in user service test

---

.github/workflows/tests.yaml

This PR introduces a GitHub Actions workflow that automatically runs the test suite whenever a pull request is opened. The goal is to ensure that all changes meet the expected quality standards before merging.

[_]: ci/workflow-to-run-tests-on-PRs

---

src/webhooks/handleInvoiceCompleted.ts
tests/src/webhooks/handleInvoiceCompleted.test.ts

This PR introduces a new test suite for `handleInvoiceCompleted`, ensuring its core functionality is properly validated. Since this test will be required in upcoming PRs, it has been added separately to keep changes isolated and facilitate future modifications.
**What:**
- Implemented a dedicated test for handleInvoiceCompleted, covering key scenarios related to user updates, subscriptions, and invoice processing.
- Separated this test into its own PR to ensure incremental development and to keep upcoming changes focused.
- Improved test coverage, making it easier to validate future modifications without introducing regressions.
**Why:**
- Prepares the codebase for future improvements: This test will serve as a foundation for validating changes in subsequent PRs.
- Encourages better …

[_]: tests/handle invoice completed

---

src/webhooks/handleInvoiceCompleted.ts
tests/src/fixtures.ts
tests/src/webhooks/handleInvoiceCompleted.test.ts
tests/src/webhooks/utils/handleOldInvoiceCompletedFlow.test.ts

This PR integrates the previously extracted function for handling user subscriptions and workspace storage updates into the `invoice.payment_succeeded` webhook event. This ensures that user data is correctly updated when a payment is successfully processed, whether the user is subscribed to an individual plan or a business workspace.
**What:**
- Integrated the extracted function into the `invoice.payment_succeeded` webhook to handle both user subscriptions and workspace storage updates upon successful payment.
- Ensured that new users are properly initialized, while existing users have their subscriptions and storage correctly updated.
- Improved code organization and maintainability by centralizing user billing updates within the correct webhook event.
**Why:**
- Maintains modularity: …

[_]: feat/implement user drive updates

---

src/services/payment.service.ts

Allow to search for a plan by its Id plan at checkout.

[_]: feat/show-plans-with-not-show

---

src/controller/products.controller.ts
src/services/tiers.service.ts
tests/src/controller/payments.controller.test.ts
tests/src/controller/products.controller.test.ts
tests/src/services/tiers.service.test.ts
tests/src/utils/initializeServer.ts

Now, we return whether the user can use the backup product in `GET /products`. As the backups can only be used as the antivirus, we return `backups: true|false` depending on the subscription or lifetime.
In this way, we can block the backup tool if the user does not have a subscription/lifetime of new products.

[_]: feat/available products depending on tier

---

src/controller/payments.controller.ts
tests/src/controller/payments.controller.test.ts
tests/src/controller/products.controller.test.ts
tests/src/fixtures.spec.ts
tests/src/fixtures.ts

This PR introduces the ability to apply promotion codes to object storage subscriptions.

[MKT-499]: feat/allow promotion codes for obj storage subscription

---

tests/src/services/tiers.service.test.ts

This PR implements use cases to check that the function getProductsTier works as expected.

[_]: tests/getProductsTier use cases

---

src/controller/products.controller.ts
tests/src/controller/products.controller.test.ts

This PR implements a hot fix where we return the featuresPerService key to return the same pattern as when the user has a tier or not.

[_]: hotfix/object returned when the user plan is free

---

src/controller/payments.controller.ts
src/services/payment.service.ts
tests/src/controller/payments.controller.test.ts

Include customer email in error log, and changed the error tag in the log to be more identifiable.

[_]: fix/include customer email in error logging for customer creation

---

src/controller/checkout.controller.ts
src/errors/Errors.ts
src/services/payment.service.ts
tests/src/controller/checkout.controller.test.ts
tests/src/controller/payments.controller.test.ts
tests/src/fixtures.ts
tests/src/services/payment.service.test.ts

This PR implements a new endpoint that creates a subscription (`POST /checkout/subscription`) in the checkout controller and also includes its tests.

[_]: feat/create subscription

---

src/controller/checkout.controller.ts

This PR fixes the user address header to get the price by its ID and its taxes.

[_]: fix/user address

---

src/controller/checkout.controller.ts
src/services/payment.service.ts
tests/src/services/payment.service.test.ts

This PR enables the automatic tax when creating subscriptions and creating invoices.

[_]: feat/enable automatic tax for subscriptions and invoices

---

src/controller/checkout.controller.ts
tests/src/controller/checkout.controller.test.ts

This PR creates the customer with `country` and `postal code` so that Stripe can use the billing address to dynamically calculate taxes and charge the user for those taxes.

[_]: feat/create customer with postal code and country

---

src/controller/checkout.controller.ts

This PR uses the name the user enters to complete the “Invoice” section in the integrated checkout.
The name can be:
* Particular name
* Company name (if the user is purchasing a b2b plan)

[_]: feat/add customer name when creating it

---

src/webhooks/handleInvoiceCompleted.ts

This PR adds a return once the object storage is applied.

[_]: hotfix/return when applying obj storage

---

src/controller/checkout.controller.ts
src/services/payment.service.ts
tests/src/controller/checkout.controller.test.ts

This PR gets the user address from the query params instad of the headers.

[_]: feat/allow fetch price without taxes

---

src/services/tiers.service.ts

This PR gets the correct product to check if the user has access to antivirus or not when he purchased a lifetime plan.

[_]: fix/get the allowed product Id for lifetime plans

---

src/webhooks/handleInvoicePaymentFailed.ts

This PR correctly handles failed payments for object storage subscriptions.
Previously, we assumed that invoices would contain only one line item. However, due to the tiered pricing model (0–1024 GB and 1025+ GB), invoices may contain multiple line items for the same product.
The logic has been updated to check every invoice line items and identify whether any of them correspond to the object storage product (based on the product metadata). If found, the corresponding object storage account is suspended.

[_]: fixpayment failed for object storage subscriptions

---

tests/src/controller/checkout.controller.test.ts

This PR aims to improve the consistency of some tests.

[_]: tests/use query object to pass the query parameters

---

package.json
src/app.ts
src/controller/customer.controller.ts
src/server.ts
src/services/cache.service.ts
src/services/payment.service.ts
src/webhooks/handleInvoiceCompleted.ts
tests/src/controller/customer.controller.test.ts
tests/src/fixtures.ts
tests/src/services/cache.service.test.ts
tests/src/services/payment.service.test.ts
tests/src/webhooks/handleDisputeResult.test.ts
yarn.lock

This PR adds a new endpoint to retrieve all promotional codes associated with a user, based on the coupons we've previously tracked.
This allows the client to handle these codes when needed, improving the flexibility of features like exclusive theme activation for users who subscribed using specific coupons.

[_]: feature/expose redeemed coupons endpoint

---

src/webhooks/events/invoices/InvoiceCompletedHandler.ts
tests/src/webhooks/events/invoices/InvoiceCompletedHandler.test.ts

This PR implements product-specific handlers for processing completed invoices, with distinct logic for legacy products and current tiered products. The handlers manage storage allocation, workspace configuration, and tier management based on the product type and subscription model.
**Old Product Handling:**
- Simple storage updates: Direct storage capacity updates for legacy products
- Backward compatibility: Maintains support for products predating the tier system
**New Product Handling:**
- Drive feature application: Configures storage and workspace features based on subscription type
- VPN feature application: Activates VPN capabilities according to the user’s tier
- Intelligent tier management: Determines optimal tier configuration for lifetime purchases
**Lifetime Plan Logic:**
The …

[PB-4285]: refactor/handle old and new products in invoice completed handler

---

src/cli/load-license-codes.ts
src/controller/payments.controller.ts
src/server.ts
src/services/licenseCodes.service.ts
tests/src/fixtures.ts
tests/src/services/licenseCodes.service.test.ts
tests/src/utils/factory.ts

This PR implements another way to redeem codes. If the code is associated with a price that corresponds to the level products, their characteristics will be added. Otherwise, we only change the storage.

[PB-4719]: feat/apply tier if needed when redeeming license codes

---

src/services/licenseCodes.service.ts
tests/src/fixtures.ts
tests/src/services/licenseCodes.service.test.ts

This PR get the product ID from a license code so we can use it to check if there is a tier to use or not.

[_]: fix/get product id from license code price ID

---

src/services/licenseCodes.service.ts
tests/src/services/licenseCodes.service.test.ts

This PR get the lifetime tier instead of the subscription tier when subscribe the user.

[_]: feat/apply the lifetime tier

---

src/webhooks/events/invoices/InvoiceCompletedHandler.ts
tests/src/webhooks/events/invoices/InvoiceCompletedHandler.test.ts

This PR implements two utility functions for the `invoice.payment_succeeded` webhook handler, focusing on coupon tracking and cache management.

[PB-4285]: refactor/user-coupon relationship and clear user cache

---

tests/src/webhooks/utils/handleCancelPlan.test.ts
tests/src/webhooks/utils/handleUserFeatures.test.ts

This PR adds the service factory that we create in each test, avoiding duplication of each service.

[_]: feat/using test service factory in each test

---

src/webhooks/index.ts
tests/src/webhooks/webhook.test.ts

This PR implements the enhanced Invoice Completed Handler for  the Stripe's event `invoice.payment_succeeded`.

[PB-4285]: feat/use the improved handler in Stripe webhook

---

src/controller/payments.controller.ts
tests/src/controller/payments.controller.test.ts

This PR aims to remove useless EPs and unused functions so that we don't have to maintain code that is no longer used. In addition to removing all unused code.

[PB-4739]: refactor/removing dead code and useless EPs

---

src/app.ts
src/controller/products.controller.ts
tests/src/controller/products.controller.test.ts

This PR uses the user-tier relationship as source of truth to return the available products for the user.

[_]: fix/use user-tier relationship to return the available products

---

src/controller/products.controller.ts
tests/src/controller/products.controller.test.ts

This PR allows only users who have paid for a new plan to use backups. This means that only users with a user-tier relationship in our DB will have any new products activated (according to each product's specifications).

[_]: feature/apply products based on user tier relationship

---

src/core/users/Tier.ts
tests/src/fixtures.ts

This PR implements new features in the Tier object.

[PB-4998]: feat/add more products

---

src/services/products.service.ts
tests/src/services/products.service.test.ts

This PR merges all user tiers into one to return all available products from their individual and B2B plans to the user.

[_]: feature/merge both individual and business tiers

---

src/services/licenseCodes.service.ts
src/services/payment.service.ts
tests/src/services/licenseCodes.service.test.ts

This PR fetches the price by its Id directly from Stripe instead of using the functions where we filter by `maxSpaceBytes` and unnecessary metadata fields.

[_]: fix/fetch the price by id directly from Stripe
