internxt/payments-server

- src/webhooks/handleCheckoutSessionCompleted.ts
Throws an error instead of returning when the user creation/update fails, forcing the caller to handle that error (usually returning a 500 HTTP status code)
> [_]: fix(checkout): let the payment fail

- src/webhooks/index.ts
Since SEPA payments are identified by an async checkout session we need to start handling this event (already activated from the Stripe dashboard).
> Handle async checkout event for SEPA payments

- tests/src/controller.test.ts
The test: `controller e2e tests 👉🏼 PUT /subscriptions 👉🏼 happy path` was failing due to `getUserSubscription` not being declarated:
```json
{
"req": {
"method": "PUT",
"url": "/subscriptions",
"hostname": "localhost:80",
"remoteAddress": "127.0.0.1"
},
"res": {
"statusCode": 500
},
"err": {
"type": "TypeError",
"message": "paymentService.getUserSubscription` is not a function",
"stack": "TypeError: paymentService.getUserSubscription is not a function\n    at Object.<anonymous> (/home/joan/internxt/payments/src/controller.ts:98:58)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
},
"msg": "paymentService.getUserSubscription is not a function"
}
```
> [_] fix: add missing payment service mock

- src/services/PaymentService.ts
Allows using promotion codes upon checkout. 
Docs: https://stripe.com/docs/payments/checkout/discounts#promotion-codes
> Allow promotion codes

- src/services/PaymentService.ts
problems with Stripe because you can only specify allow-promotional-code or discounts. So I made a ternary to check if there is coupon, then only discount param is added, otherwise allow_promotional_code.
> [_]: fix/allow-coupons

- fastify-jwt.d.ts
- package.json
- src/app.ts
- src/cli/load-license-codes.ts
- src/controller.ts
- src/core/users/LicenseCode.ts
- src/core/users/LicenseCodeRepository.ts
- src/core/users/MongoDBLicenseCodesRepository.ts
- src/server.ts
- src/services/LicenseCodesService.ts
- src/services/PaymentService.ts
- yarn.lock
Allows the service to accept external providers who share with us the codes of the purchases made by their customers:
- They provide an Excel of codes with the related plans. We use the Stripe Price IDs to relate it to our payments processor which is Stripe
- Then, we just adjust the data to match the same data that will be existing on any purchase made via Stripe, except the payment method.
> [MKT-94]: feat/allow-external-providers

- src/services/PaymentService.ts
The problem was that pending_invoice_items_behavior had the value 'include_and_require' which is not allowed by this parameter and gave an error when the user tried to redeem a code from an external provider. So, the value has been changed to 'include' which will include any pending invoice items and will create an empty draft invoice if no pending invoice items exist.
> [_]: Fix/redeem codes to external codes

- src/controller.ts
- src/services/PaymentService.ts
**PROBLEMS:**
The user is not charged the price he should be when using the free trial. We should add 3 months free and, once finished, charge the user for the plan without the 3-month discount.
If the user wants to upgrade his plan with the free trial, he will not be able to upgrade (either to a coupon code plan or to a normal plan).
**HOW TO SOLVE IT:**
If the user uses the free trial offer, we must set prorations_behavior to 'none'. If we want to upgrade a plan, we must add proration_behavior to 'create_proprations' and billing_cycle_behavior to 'now'. 
We have added trial_end: 'now' so that if the user upgrades his plan to have a free trial, he can do it without any problem.
**INFO:**
https://stripe.com/docs/billing/subscriptions/billing-cycle#prorating-changes-through-the-api
> [PB-706/PB-692]: fix/trial when cancelling plan

- src/controller.ts
- src/services/PaymentService.ts
- src/webhooks/index.ts
**PROBLEM:**
When the user update the subscription, Stripe request for the 3D Secure again.
**FIX:**
I think the problem is `billing_cycle_anchor` because the user has to pay again, so let's remove that until Stripe give us a solution.
If the problem persists, I will look for another solution.
> [_]: fix/remove billing cycle param

- src/controller.ts
- src/services/PaymentService.ts
Now, when a user updates a subscription, we request the 3DSecure if needed.
> [_]: feat/add 3DSecure params

- src/services/PaymentService.ts
**EXPECTED BEHAVIOR:**
We should always charge the user when he upgrades to another subscription, regardless of the plan.
**PROBLEM:**
When the user upgrades the subscription to another price of the same billing frequency (sub monthly -> sub monthly), then he pays nothing until the next billing. Eg.:
The user purchases an annual subscription on August 10 and upgrades it on September 15, he will pay nothing until August 10 of the following year.
[Example](https://dashboard.stripe.com/customers/cus_PHZXnZmj2eKqia).
**FIX:** 
Now, we set the billing cycle anchor to now to charge the price at the time regardless of which subscription the user wants to upgrade to.
[Stripe docs](https://stripe.com/docs/billing/subscriptions/billing-cycle#changing).
> [_]: fix/charge the total price when updating sub

- src/services/PaymentService.ts
**EXPECTED BEHAVIOR:**
When the user has a subscription and wants to cancel it, we offer 3 months free. If the user selects the offer, then we apply a 3 month free trial to that same sub they already have.
**PROBLEM:**
Using billing_anchor_tag="now" is not possible while trying to add a free trial.
**FIX:**
We add the billing_anchor_tag parameter only when the user tries to update a normal subscription through additionalParams. Thus, the updateSub function has only the basic parameters to work in all cases.
> [_]: fix/prevent cancellation flow

- src/app.ts
- src/controller-migration.ts
- src/controller.ts
- src/core/users/User.ts
- src/services/PaymentService.ts
Currently, the `/subscriptions` endpoint does not make a request to  Stripe if the user has a lifetime subscription, it is not required for its use case so it makes sense.
Therefore, we need a similar temporal endpoint that brings the productId (if the user has 200gb, 1tb plans, etc) from stripe, even if the user has lifetime. 
This will also start sending the productId to /subscriptions, however, it is harmless. @masterprog-cmd  feel free to confirm if it affects something.
Example of returned data
```json
{
"planId": "prod_NXNb9cOS28ubg5",
"type": "lifetime",
"uuid": "7bd7ee09-c704-452b-bb0d-51302e9884b5"
}
```
When you adquire a lifetime plan, a subscription is not created, Stripe does not create subscriptions for prices of 'one_time' type. The only way is to get them through invoices. …
> chore: added temporal endpoint for plans migration

- src/controller.ts
- src/services/CacheService.ts
- src/services/PaymentService.ts
Modify subscriptions endpoint to allow the retrieval of B2B subscriptions based on the metadata field on product `type="business"`. All products missing this metadata field are treated as if they where `"individual"` plans.
> [PB-2117]: feat/get active b2b subscriptions

- src/controller.ts
- src/services/PaymentService.ts
- src/services/UsersService.ts
- src/webhooks/handleCheckoutSessionCompleted.ts
When creating a checkout session if the product is B2B based on the metadata `type === 'business'` quantity becomes modifiable using Stripe's `adjustable_quantity` property, where `minimum` and `maximum` are set based on price metadata properties `minimumSeats` and `maximumSeats` respectively.
When handleCheckoutSessionHook is triggered quantity is taken from lineItems in order to call initializeWorkspace with `maxSpaceBytes: newStorageBytes * seats`.
> [PB-2194]: feat/seat count handling on b2b subscriptions

- src/controller.ts
- src/core/users/MongoDBProductsRepository.ts
- src/core/users/ProductsRepository.ts
- src/core/users/User.ts
- src/server.ts
- src/services/PaymentService.ts
- Capability to list for business subscriptions
- Capability to dynamically add new products as business or individual types (via database)
`GET /subscriptions?userType={'individual'/'business'}`
- When the `userType`:
- is not provided or equals 'individual', the behavior is the already existent one.
- equals 'business', the API will match what the new collection 'products' has with what Stripe says. The match is established using the payments gateway product ID (in this case Stripe). Therefore, for this to work, we need to add a document for each product we have, establishing the `userType` and the product ID, so when listing subscriptions, the match happens.
- Cache business subscriptions as we do with the individual ones
- Integrate the new dynamic system with individual subscriptions
> [PB-2222]: feat/request-subscriptions-for-business

- src/controller.ts
- src/core/users/User.ts
- src/services/PaymentService.ts
- src/services/UsersService.ts
- src/webhooks/handleCheckoutSessionCompleted.ts
- src/webhooks/handleSetupIntentSucceded.ts
- src/webhooks/handleSubscriptionUpdated.ts
- src/webhooks/index.ts
- Add/Update webhooks to update the payment method according to the `userType` (`individual`, `business`)
- Modify `setup-intent` to add the `metadata` field. From the frontend, they need to send the appropriate `userType` to handle the `setup_intent.succeeded` event and update the appropriate subscription.
- Update the workspace storage if the `userType` is `business`
- SDK : https://github.com/internxt/sdk/pull/216
> [PB-2115] feat: b2b update subscription payment method

- src/services/PaymentService.ts
Use the currency that the user has selected in the client side to create the checkout. 
Currently, when the user selects a plan to pay with $, € is displayed because, when the checkout is created, the default currency of the product is used.
Now, we use the currency that the user selected in the client directly because the plans have been created as multi-currency products.
> [_]: fix/allow-product-currency-parametrization-on-checkout

- src/controller.ts
- src/services/PaymentService.ts
In production, the coupon ID is used to create the session with the discount automatically added. Now, the promotion code ID is used to do so.
Using the promotion code Id and not the coupon Id gives us the advantage of being able to use disposable promo codes. That is, we can configure them with an expiration date to be unusable, so we can use the promotion code (the same code that is added in the checkout when the user must add it manually). This allows us to have more flexibility when redeeming coupons.
Now, the promotion code ID and not the coupon ID is used when creating the checkout. And because of this, an endpoint has been enabled to get the promotion code information by name, where you get the id, the percentage/fixed price that is discounted.
The same flow is maintained as it is …
> [MKT-408]: feat/use promotion code ID instead of coupon ID

- src/services/PaymentService.ts
- src/webhooks/handleInvoiceCompleted.ts
Check that the payment is not for a b2b product to proceed with the logic of `invoices.payment_succeeded`
> [_]: fix/exclude-business-products-from-invoice-payment-succeeded

- src/controller.ts
- src/services/PaymentService.ts
Check if the user has a subscription before creating another one in order not to have several products activated per user.
> [_]: fix/check if there is a subscription before creating one

- src/services/PaymentService.ts
removing the sub checkout before creating the subscription and thus allowing the user to purchase a sub.
> [_]: fix/remove the sub check before creating the subscription

- src/services/ObjectStorageService.ts
- src/webhooks/handleInvoiceCompleted.ts
- src/webhooks/handleInvoicePaymentFailed.ts
- src/webhooks/index.ts
Changes: 
- Adds a basic handling of the lifecycle of an Object Storage user 
- If the `invoice.payment_failed` triggers, the account is deactivated
- If the `invoice.payment_succeeded` triggers, the account is reactivated (if proceeds)
- Automate the account removal signal if the payment_failed happens more than N times.
This is not still included as we do not offer a way of changing the payment method on the current Object Storage UI, therefore situations like expired cards could happen, thus, we do not want to perform an account removal of a customer who has been paying properly for years and forgot to change the card used to pay.
> [_]: feat/basic-object-storage-account-lifecycle-management

- src/controller.ts
- src/services/PaymentService.ts
The invoice for “free” one time payments (amount = 0€) is paid at the time it is created, so the customer secret does not exist. To solve this problem, we send the invoice status to the customer to avoid payment confirmation, only if the `status = 'paid'`.
> [_]: fix/undefined client secret for invoices with 100% off discount

- src/services/PaymentService.ts
Return active and trial subscriptions to get the subscription if the user used the offer to avoid cancellation. This way we show the paid plan to which the free trial has been added and not the free plan.
> [PB-3066]: fix/return active and trialing subscriptions

- src/webhooks/handleInvoiceCompleted.ts
Avoid getting the customerId so many times and run the obj storage handling only if necessary.
> [_]: fix/avoid getting the customerId so many times

- src/controller.ts
- src/webhooks/handleInvoiceCompleted.ts
- Return the correct plan for both individual and subscriptions, because when the individual sub is lifetime, `type=lifetime` is returned for both subs (individual and business).
- Prevent cancellation of business subscriptions when the product is an individual lifetime. Now we filter the product and check if is for individuals before canceling it.
- Prevent lifetime field update if the sub is not individual.
> [_]: fix/avoid canceling business sub, avoid updating the lifetime field when it is not needed and return the correct sub for each user type

- .github/workflows/build-and-deploy.yml
- .github/workflows/build-and-publish-preview.yaml
- .github/workflows/deploy-pr-preview.yaml
- .github/workflows/slash-command-dispatcher.yaml
Update the node version for each CI/CD pipeline to match the minimum required engine in package.json (Node v20).
This finally solves the issue https://github.com/internxt/payments-server/issues/122.
> [_]: feat/modify CI/CD pipeline configurations to use node 20

- .github/workflows/sonarcloud-analysis.yml
- src/webhooks/index.ts
Before updating the user's lifetime status and storage, we check whether the payment is [fully refunded](https://docs.stripe.com/api/charges/object#charge_object-refunded) or not to do that. So when we do a partial refund, the user keeps both the Lifetime label and the space purchased in Drive.
> [PB-3407]: fix/wrong plan display when partial refund is made for lifetime plans

- .github/workflows/build-and-deploy.yml
- .github/workflows/build-and-publish-preview.yaml
- .github/workflows/deploy-pr-preview.yaml
- .github/workflows/slash-command-dispatcher.yaml
- .github/workflows/sonarcloud-analysis.yml
- Dockerfile
- README.md
- infrastructure/development.Dockerfile
- infrastructure/preview.Dockerfile
- package.json
- yarn.lock
**What's new:**
- Minimum node versions has been updated to use the LTS - v22.12.0.
- Node version in GH Workflows has been updated.
- Node version in docker files (infra) has been updated.
- Also updated @types/node package to keep up with the latest types for node v22.
Related to #131 (Upgrade to Node v22)
> [_]: chore/upgrade to node v22

- src/controller/payments.controller.ts
- src/services/payment.service.ts
- tests/src/mocks/index.ts
- tests/src/services/payment.service.test.ts
- tests/src/webhooks/handleDisputeResult.test.ts
To get the user invoices, it is necessary to use the `userType` query parameter to filter the invoices based on the product type.
If the user wants `business invoices`, then the invoices will be filtered to get ONLY business product invoices. Otherwise, the endpoint will return ONLY the `individual invoices` (subscription + lifetime).
Object storage invoices have been automatically avoided.
**Nice to know**
The filter will be only applied if the `subscription Id` is not sent, as it does not make sense to filter by `userType` if the request is made for a specific `subscription Id`.
> [PB-3585]: fix/filter invoices depending on the item type

- src/services/payment.service.ts
New Vat ID to allow the users from that country to purchase an S3/business plan using the tax ID. 
The new country is **Belgium**.
> [_]: feat/Belgium Vat ID

- package.json
- tests/src/fixtures.spec.ts
- tests/src/fixtures.ts
This PR refactors the way mocks are created and utilized in test cases. Previously, mocks were defined as constant variables, which limited flexibility and could lead to unintended state persistence across multiple tests.
With this update, mocks are now encapsulated within functions, ensuring that each test case receives a fresh and isolated mock instance when needed. This approach enhances test reliability, reduces potential side effects, and improves maintainability by providing greater control over mock initialization.
By implementing this change, we improve test consistency and make the mocking strategy more scalable for future test expansions.
> [_]: tests/new-test-fixtures

- src/core/users/MongoDBTiersRepository.ts
- src/core/users/MongoDBUsersTiersRepository.ts
- src/core/users/Tier.ts
- src/services/tiers.service.ts
- tests/src/core/users/MongoDBTiersRepository.test.ts
- tests/src/core/users/MongoDBUsersTiersRepository.test.ts
- tests/src/fixtures.spec.ts
- tests/src/fixtures.ts
- tests/src/payments.controller.test.ts
- tests/src/services/tiers.service.test.ts
This PR introduces the implementation of the user-tier relationship in MongoDB. The feature allows users to be linked to different tiers, ensuring that the assigned subscription or lifetime plan is correctly stored and retrieved.
- Created MongoDBUsersTiersRepository to handle user-tier assignments.
- Implemented methods to:
- Insert a tier for a user.
- Retrieve all assigned tiers for a user.
- Update a user's assigned tier.
- Remove a specific tier from a user.
- Delete all tiers assigned to a user.
- Added unit tests to verify that the repository correctly manages the user-tier relationships.
- Added unit tests to verify that the repository correctly retrieves the requested tier.
> [PB-3884]: feat/store-users-tiers-relationship

- src/webhooks/handleSubscriptionCanceled.ts
- src/webhooks/index.ts
- src/webhooks/utils/handleOldInvoiceCompletedFlow.ts
- tests/src/webhooks/handleSubscriptionCanceled.test.ts
This pull request introduces functionality to remove the association between users and their respective tiers within our local databases. It ensures that upon certain webhook events, users' subscriptions are either canceled or downgraded to the free plan, effectively managing their access levels.
Implementing this feature is crucial for maintaining accurate user-tier relationships and ensuring that our system reflects the current subscription status of each user. By automating the cancellation or downgrading process through webhook events, we enhance operational efficiency and provide users with a seamless experience that aligns with their subscription choices.
> [PB-3915]: feat/handle subscription canceled

- src/controller/payments.controller.ts
Enables an endpoint to generate a token to enable subscriptions with trials for the PcComponentes campaign.
> [_]: feat/generate-trial-token

- src/webhooks/handleInvoiceCompleted.ts
- src/webhooks/handleLifetimeRefunded.ts
- src/webhooks/handleSubscriptionCanceled.ts
- src/webhooks/utils/handleCancelPlan.ts
This PR implements logs to track flows when cancelling a subscription/lifetime. With these logs, we can keep track of when a user cancels a plan.
> [_]: feat/cancelling-subscription-lifetime-logs

- src/services/tiers.service.ts
- src/webhooks/handleInvoiceCompleted.ts
- src/webhooks/handleSubscriptionCanceled.ts
- src/webhooks/utils/handleCancelPlan.ts
- src/webhooks/utils/handleUserFeatures.ts
- tests/src/services/tiers.service.test.ts
- tests/src/webhooks/utils/handleCancelPlan.test.ts
- tests/src/webhooks/utils/handleUserFeatures.test.ts
This PR handles stacking lifetimes cases - when the user purchases a plan (`invoice.payment-succeeded`) and when a lifetime is refunded (`charge.refund`).
We need to handle the stack of storage when the lifetime plan is paid. Also, we need to reset the user tier to free when the last lifetime is refunded.
> [PB-3908]: feat/apply stack of lifetime storage

- src/app.ts
- src/controller/payments.controller.ts
- src/core/users/DisplayPrice.ts
- src/core/users/User.ts
- src/services/payment.service.ts
- tests/src/controller/payments.controller.test.ts
This PR returns the product ID of the assigned Tier, both for subscriptions and lifetime. In this way, we can identify which product/tier the user has at any given moment. It is useful especially for Current tagging in the app web, for example.
> [_]: feat/return the lifetime product id the user has

- src/controller/products.controller.ts
- tests/src/controller/products.controller.test.ts
Instead of causing unintended behavior or failing silently, the system will now return a well-defined response and log the issue appropriately. This ensures that client-side consumers and internal systems get clear feedback when a user or subscription is missing.
> [PB-4190]: fix/improve error handling when user or subscription is not found

- fastify-jwt.d.ts
- src/app.ts
- src/controller/products.controller.ts
- src/core/users/MongoDBTiersRepository.ts
- src/server.ts
- src/services/products.service.ts
- tests/src/controller/products.controller.test.ts
- tests/src/fixtures.ts
- tests/src/services/products.service.test.ts
This PR implements a new endpoint to get the user's tier if he has one, depending on whether the individual tier or the business tier is requested.
- If the individual tier is requested, it is searched by the tier associated to the user. 
- If the business tier is requested, we search if the user has any active business subscription and if he belongs to a Workspace (as if he“belongs” to the active subscription of the owner of another workspace). We obtain the all tiers related to the workspaces he pertain, filter by the highest one and return it.
> [PB-4137]: feat/get higher tier available for user

- src/controller/payments.controller.ts
- src/services/customerSync.service.ts
- src/services/payment.service.ts
- src/services/users.service.ts
This RP gets the correct customer when trying to get the customer ID to make a payment. For this case, what we do is the following:
- We check that it exists in the local database using the uuid. If it exists, we return the existing one.
- If it does not exist by uuid, we obtain the customerIds associated to the user's email in Stripe.
- If it has any customerId, we check if any of them match with the one we have in the local database. If it is the case, we check if the uuid matches. If they do not match, then we update the uuid of that item in the collection and return the existing customer Id. 
If none of the above steps is successful, then we create a customer id.
> [_]: hotfix/get correct customer before payment

- src/services/customerSync.service.ts
If customer does not exist in payments DB but it exists in Stripe, catch the error thrown by the function findUserByCustomerID
> [PB-4338]: fix(customer-creation)/customer creation

- src/webhooks/handleInvoiceCompleted.ts
- src/webhooks/handleSubscriptionCanceled.ts
- tests/src/webhooks/handleInvoiceCompleted.test.ts
This PR handles the user-coupon relationship for subscriptions as Stripe sends different objects in the event depending on the product (subscription or lifetime).
> [_]: fix/users-coupon relationship for subscriptions

- src/controller/checkout.controller.ts
- src/services/payment.service.ts
- tests/src/controller/checkout.controller.test.ts
- tests/src/fixtures.ts
- tests/src/services/payment.service.test.ts
This PR introduces a new endpoint to create a Stripe Payment Intent, allowing users to purchase one-time products such as lifetime plans.
The endpoint is exposed via `POST /checkout/payment-intent`, and includes full test coverage to ensure correct behavior.
> [_]: feat/create payment intent

- fastify.d.ts
- src/controller/checkout.controller.ts
- src/services/payment.service.ts
- tests/src/controller/checkout.controller.test.ts
- tests/src/fixtures.ts
- tests/src/services/payment.service.test.ts
This PR introduces a new endpoint to retrieve a product price by its ID, including tax calculations.
The endpoint is GET /checkout/price-by-id.
It returns:
* The base price (without taxes),
* The calculated tax amount (based on the user's location),
* The total amount (price + taxes).
This allows the frontend to display a detailed price breakdown to the user before completing the purchase.
> [_]: feat/get price by id

- fastify.d.ts
- src/controller/checkout.controller.ts
- src/services/payment.service.ts
- tests/src/controller/checkout.controller.test.ts
- tests/src/controller/payments.controller.test.ts
- tests/src/fixtures.spec.ts
- tests/src/fixtures.ts
- tests/src/services/payment.service.test.ts
This PR updates the tax calculation logic during the purchase process to ensure that discounts are correctly accounted for. The main changes include:
* Adjusted the tax calculation to apply discounts before calculating taxes, resulting in accurate tax amounts based on the final price.
* Added functionality to retrieve tax-inclusive product information, allowing for better display of final prices to users.
* Calculate a tax estimate following Stripe's documentation:
* Customer billing address if exists.
* IP address if exists
* Calculate final taxes if the customer is new and the IP address and billing address (country) do not match.
* Update fixtures and test cases to reflect the new tax calculation logic and ensure consistency with the adjusted implementation.
- Discounts are applied …
> [_]: feat/calculate taxes using discounts

- src/controller/checkout.controller.ts
- tests/src/controller/checkout.controller.test.ts
This PR updates the GET /price-by-id endpoint to return two structured objects:
Price:
Includes all relevant pricing information:
- `amount`: Base price in cents
- `type`: Either 'individual' or 'business'
- `interval`: 'year' or 'lifetime'
- `decimalAmount`: Price in euros
- `product`: ID of the associated product
- `businessSeats`: Minimum and maximum number of seats required (for business plans)
Taxes:
Contains tax-related details calculated based on the request context:
- `tax`: Tax amount in cents
- `decimalTax`: Tax amount in euros
- `amountWithTax`: Total amount (price + tax) in cents
- `decimalAmountWithTax`: Total amount in euros
With this structure, the frontend has all the necessary information to accurately display pricing and tax breakdowns within the integrated checkout …
> [_]: fix/price in checkout

- src/controller/checkout.controller.ts
This PR adds a new query parameter to the customer creation endpoint that allows using the user's company name when available.
If the companyName is provided, it will be used as the Stripe customer's name. Otherwise, the user's personal name will be used as a fallback.
> [_]: feat/use company name if provided to create customer

- src/services/tiers.service.ts
This PR throws the error back to the parent if the workspace is not destroyed.
> [_]: fix/throw the error back to the parent

- src/controller/checkout.controller.ts
- tests/src/controller/checkout.controller.test.ts
This PR uses the correct customer name query parameter sent from the client side.
> [_]: fix/customer name query param when creating customer

- src/controller/payments.controller.ts
- src/services/payment.service.ts
- tests/src/controller/checkout.controller.test.ts
- tests/src/controller/payments.controller.test.ts
- tests/src/fixtures.ts
- Implemented tax collection logic for new object storage subscriptions, aligning with our billing requirements.
- Updated JWT handling to skip verification for public object storage routes.
- Removed unused or deprecated endpoints related to legacy object storage flows.
- Refactored route structure to follow best practices and improve clarity and maintainability.
> [PB-4388]: feat/activate automatic tax when creating sub

- src/errors/Errors.ts
- src/services/payment.service.ts
- src/webhooks/handleFundsCaptured.ts
- tests/src/fixtures.ts
- tests/src/webhooks/handleFundsCaptured.test.ts
This PR adds logic to handle the event triggered after payment method verification when Stripe captures the funds.
When Stripe confirms that the payment method has sufficient funds (by capturing 1 €), the PaymentIntent is immediately cancelled to avoid charging the user. Then, the object storage subscription is created and the associated account is initialized.
This flow ensures the payment method is valid without incurring fees or creating subscriptions with invalid payment sources.
> [PB-4396]: feat/function to handle the captured funds

- src/constants.ts
- src/controller/payments.controller.ts
- src/webhooks/handleFundsCaptured.ts
- src/webhooks/handleInvoicePaymentFailed.ts
- src/webhooks/handleSubscriptionUpdated.ts
- src/webhooks/index.ts
- tests/src/webhooks/handleFundsCaptured.test.ts
- tests/src/webhooks/webhook.test.ts
Add handling for Stripe’s `payment_intent.amount_capturable_updated` webhook that fires when the €1 card-verification hold becomes capturable.
If we do nothing, Stripe will settle that €1 as an actual charge a few days later. Voiding the intent keeps onboarding friction-free and prevents surprise charges.
- Listen for `payment_intent.amount_capturable_updated`.
- Immediately cancel the Payment Intent, voiding the €1 hold.
- Create the Object-Storage subscription.
- Initilize the customer’s Object-Storage.
> [PB-4396]: feat/add event to create subscription and initialize object-storage 

- src/cli/load-license-codes.ts
- src/controller/payments.controller.ts
- src/server.ts
- src/services/licenseCodes.service.ts
- tests/src/controller/payments.controller.test.ts
- tests/src/fixtures.ts
- tests/src/services/licenseCodes.service.test.ts
This PR applies the tier to a user if the price ID of the redeemed code matches any product associated with a tier. When a code is redeemed, the product's price ID is checked against the price IDs of all tiered products. If a match is found, the corresponding tier is applied. If not, we just update the storage.
> [PB 4719]: feature/apply tier if necessary when redeeming the code

- src/services/payment.service.ts
- tests/src/services/payment.service.test.ts
This PR improves the total we pass to the crypto invoice by retrieving the total of the invoice to be paid instead of creating a preview of an upcoming invoice.
> [PB-3649]: feat/retrieve the pre created invoice instead of creating a preview

- package.json
- src/cli/load-license-codes.ts
- src/server.ts
- tests/src/fixtures.ts
- tests/src/helpers/services-factory.ts
- yarn.lock
This PR updates the Stripe SDK from v15.10.0 to  v16.12.0. We need to update the Stripe SDK to v18.X in order to use `Klarna` as an allowed payment method when creating invoices.
> [PB-4735]: chore/bump stripe version to v16.12.0

- package.json
- src/cli/load-license-codes.ts
- src/server.ts
- tests/src/fixtures.ts
- tests/src/helpers/services-factory.ts
- yarn.lock
This PR updates the Stripe SDK from v16.12.0 to v17.7.0. We need to update the Stripe SDK to v18.X in order to use Klarna as an allowed payment method when creating invoices.
> [PB-4735]: chore/bump stripe version to v17.7.0

- src/services/tiers.service.ts
- tests/src/services/tiers.service.test.ts
This PR adds a condition for invoices paid outside the system, so that users who have paid an invoice using cryptocurrencies (bit2me) can use the antivirus and backup services.
> [_]: fix/return the available products for bit2me invoices

- src/controller/checkout.controller.ts
- tests/src/controller/checkout.controller.test.ts
This PR adds the insertion of the user into the database immediately after the customer is created. This change prevents the creation of multiple customers in case a payment fails, since previously the system could not verify whether the user already had a customer until the purchase was completed, at which point the user was added to the database.
This PR depends on the following:
- https://github.com/internxt/payments-server/pull/294
> [_]: fix/insert user in DB after creating customer

- src/services/products.service.ts
This PR returns an empty array when the user doesn't exist so we will return the free tier instead.
> [_]: fix/return free user when the user does not exist

- src/services/users.service.ts
- src/webhooks/handleInvoicePaymentFailed.ts
- src/webhooks/index.ts
- tests/src/webhooks/handleInvoicePaymentFailed.test.ts
- tests/src/webhooks/webhook.test.ts
This PR modifies the existing failed payment handler and adds a method to call an endpoint in gateway drive-server-wip to notify that this event has been triggered from the payment provider.
- Modified handleInvoicePaymentFailed.ts to add failed payments notification
- Added call to usersService.notifyFailedPayment(user.uuid)
- Add handleInvoicePaymentFailed unit test file
> [PB-5033]: feat/notify-failed-payment-on-invoice-payment-failed

- src/app.ts
- src/controller/business.controller.ts
- src/core/users/Tier.ts
- src/services/licenseCodes.service.ts
- src/services/storage.service.ts
- src/services/tiers.service.ts
- src/services/users.service.ts
- src/webhooks/events/invoices/InvoiceCompletedHandler.ts
- src/webhooks/handleLifetimeRefunded.ts
- src/webhooks/handleSubscriptionCanceled.ts
- tests/src/controller/business.controller.test.ts
- tests/src/fixtures.ts
- tests/src/services/licenseCodes.service.test.ts
- tests/src/services/products.service.test.ts
- tests/src/services/storage.service.test.ts
- tests/src/services/tiers.service.test.ts
- tests/src/services/users.service.test.ts
- tests/src/webhooks/events/invoices/InvoiceCompletedHandler.test.ts
- tests/src/webhooks/handleLifetimeRefunded.test.ts
- tests/src/webhooks/handleSubscriptionCanceled.test.ts
This PR modifies the Drive storage update flow to include the tierId when a user purchases or cancels a subscription.
Previously, only the storage space (`maxSpaceBytes`) was updated, but now Drive needs to know the associated tier to apply the correct policies and configurations.
> [PB-4944]: feat/pass drive tier id when updating drive storage
